runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: assets/(.*)

- url: /(.*)
  static_files: www/\1
  upload: assets/(.*)

# handlers:
# - url: /(.*\.(js|css|png|gif|jpg|svg|ttf|ico|json))$
#  static_fields: dist/\1
#  upload: dist/.*\.(js|css|png|gif|jpg|svg|ttf)
#  #catch all handlers to index.html
# - url: /.*
#  static_files: dist/index.html
#  upload: dist/index.html
