runtime: python27
api_version: 1
threadsafe: true

handlers:
# If a user access the root of the app
- url: /
  # literal regular expression for file path of index.html
  static_files: www/index.html
  # all files used when a user access the url above
  upload: www/index.html
# If a user access any path that's not the root
- url: /(.*(register|login|account|transactions|wallet|demo))$
  static_files: www/index.html
  # all files used when a user access the url above
  upload: www/index.html
# Any remaining routs, like for filed extensions
- url: /(.*)
  # \1 is referring to what's in the parenthesis directly above
  # which means the static files will directly match what's in the url bar,
  # except it will be from within the www folder
  static_files: www/\1
  # All files when a user access the routes in this handler will
  # be within the assets folder and any other subdirectory
  upload: www/assets/(.*)
